SELECT CHILD.ID
FROM ECOLI_DATA CHILD
JOIN ECOLI_DATA PARENT
ON CHILD.PARENT_ID = PARENT.ID
JOIN ECOLI_DATA GRAND
ON PARENT.PARENT_ID = GRAND.ID
WHERE PARENT.PARENT_ID IS NOT NULL AND GRAND.PARENT_ID IS NULL
ORDER BY ID