# ID가 PARENT_ITEM_ID에 없으면 더이상 업그레이드 불가능한 것임.
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO I
WHERE NOT EXISTS
(
    SELECT PARENT_ITEM_ID ITEM_ID
    FROM ITEM_TREE T
    WHERE T.PARENT_ITEM_ID = I.ITEM_ID
)
ORDER BY ITEM_ID DESC
