SELECT F.FOOD_TYPE, REST_INFO.REST_ID, REST_INFO.REST_NAME, F.FAVORITES
FROM(
    SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE) F, REST_INFO
WHERE F.FAVORITES = REST_INFO.FAVORITES AND F.FOOD_TYPE = REST_INFO.FOOD_TYPE
ORDER BY F.FOOD_TYPE DESC