SET @CNT := (
    SELECT COUNT(*)
    FROM ECOLI_DATA
);

SELECT ID
, CASE
    WHEN R / @CNT <= 0.25 THEN 'CRITICAL'
    WHEN R / @CNT <= 0.50 THEN 'HIGH'
    WHEN R / @CNT <= 0.75 THEN 'MEDIUM'
    ELSE 'LOW'
END AS COLONY_NAME
FROM (
    SELECT ID
        , ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY DESC) R
    FROM ECOLI_DATA
) RANKING
ORDER BY ID