SELECT
    EXTRACT(YEAR FROM SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM SALES_DATE) AS MONTH,
    U.GENDER,
    COUNT(DISTINCT U.USER_ID) AS USERS
FROM ONLINE_SALE O
JOIN USER_INFO U
    ON O.USER_ID = U.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY 
    EXTRACT(YEAR FROM SALES_DATE),
    EXTRACT(MONTH FROM SALES_DATE),
    GENDER
ORDER BY YEAR, MONTH, GENDER