SELECT C.CAR_TYPE, count(*) AS CARS
FROM CAR_RENTAL_COMPANY_CAR C
WHERE (
    LOCATE('열선시트', C.OPTIONS)
    OR
    LOCATE('가죽시트', C.OPTIONS)
    OR
    LOCATE('통풍시트', C.OPTIONS)
)
GROUP BY C.CAR_TYPE
ORDER BY C.CAR_TYPE