SELECT COUNT(*) FISH_COUNT, C.FISH_NAME
FROM(
    SELECT F.FISH_TYPE, N.FISH_NAME
    FROM FISH_INFO F, FISH_NAME_INFO N
    WHERE F.FISH_TYPE = N.FISH_TYPE
) C
GROUP BY C.FISH_TYPE, C.FISH_NAME
ORDER BY FISH_COUNT DESC