SELECT EXTRACT(YEAR FROM OS.SALES_DATE) AS YEAR,
       EXTRACT(MONTH FROM OS.SALES_DATE) AS MONTH,
       COUNT(DISTINCT UI.USER_ID) AS PURCHASED_USERS,
       ROUND(
           COUNT(DISTINCT UI.USER_ID) / (
               SELECT COUNT(DISTINCT USER_ID)
               FROM USER_INFO
               WHERE TO_CHAR(JOINED, 'YYYY') = '2021'
           ), 1
       ) AS PURCHASED_RATIO
FROM USER_INFO UI
JOIN ONLINE_SALE OS
    ON UI.USER_ID = OS.USER_ID
WHERE TO_CHAR(OS.SALES_DATE, 'YYYY') = '2022'
  AND TO_CHAR(UI.JOINED, 'YYYY') = '2021'
GROUP BY EXTRACT(YEAR FROM OS.SALES_DATE),
         EXTRACT(MONTH FROM OS.SALES_DATE)
ORDER BY YEAR, MONTH;