SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS I
LEFT JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
# 입양을 못 갔다. = INS에는 있지만, OUTS에는 없다.
WHERE I.DATETIME IS NOT NULL AND O.DATETIME IS NULL
# 가장 오래 있던
ORDER BY I.DATETIME
# 3마리
LIMIT 3