SELECT O.PRODUCT_ID, F.PRODUCT_NAME, O.AMOUNT * F.PRICE AS TOTAL_SALES
FROM
(
    SELECT PRODUCT_ID, SUM(AMOUNT) AMOUNT
    FROM FOOD_ORDER
    WHERE TO_CHAR(PRODUCE_DATE, 'YYYY-MM') = '2022-05'
    GROUP BY PRODUCT_ID
) O
JOIN FOOD_PRODUCT F
    ON O.PRODUCT_ID = F.PRODUCT_ID
GROUP BY O.PRODUCT_ID, F.PRODUCT_NAME, O.AMOUNT, F.PRICE
ORDER BY TOTAL_SALES DESC, O.PRODUCT_ID