SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME,
# DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d %H:%i:%s.%f') AS APNT_YMD
A.APNT_YMD
FROM APPOINTMENT A
JOIN DOCTOR D
ON D.DR_ID = A.MDDR_ID
JOIN PATIENT P
ON P.PT_NO = A.PT_NO
WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'
AND APNT_CNCL_YN = 'N'
AND A.MCDP_CD	= 'CS'
ORDER BY A.APNT_YMD