WITH RECURSIVE HOUR AS(
    SELECT 0 AS H
    UNION
    SELECT H + 1
    FROM HOUR
    WHERE H < 23
)

SELECT HOUR.H AS HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM HOUR
LEFT JOIN ANIMAL_OUTS A
ON HOUR(A.DATETIME) = HOUR.H
GROUP BY HOUR.H
ORDER BY HOUR