-- column alias (H) 로 설정
WITH HOURS(H) AS (
    SELECT 0 FROM DUAL
    UNION ALL -- UNION 사용 X
    SELECT H + 1
    FROM HOURS
    WHERE H < 23   
)

SELECT HOURS.H AS HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM HOURS
LEFT JOIN ANIMAL_OUTS
ON HOURS.H = TO_CHAR(DATETIME, 'HH24')
GROUP BY HOURS.H
ORDER BY HOURS.H