-- 회원ID, 닉네임, 총거래 금액
SELECT U.USER_ID, U.NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER U
    ON B.WRITER_ID = U.USER_ID
-- 완료된 중고 거래
WHERE B.STATUS = 'DONE'
GROUP BY U.USER_ID, U.NICKNAME
-- 총 금액이 70만원 이상
HAVING SUM(B.PRICE) >= 700000
-- 총거래금액 오름차순
ORDER BY TOTAL_SALES