SELECT P.MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
# SELECT *
FROM REST_REVIEW R
JOIN
(
    SELECT R.MEMBER_ID AS MEMBER_ID
    FROM REST_REVIEW R
    GROUP BY R.MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
) T
    ON R.MEMBER_ID = T.MEMBER_ID
JOIN MEMBER_PROFILE P
    ON P.MEMBER_ID = T.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT