SELECT H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C
ON H.CAR_ID = C.CAR_ID
WHERE C.CAR_TYPE = '세단' AND TO_CHAR(START_DATE, 'MM') = '10'
GROUP BY H.CAR_ID
HAVING COUNT(H.HISTORY_ID) > 0
ORDER BY H.CAR_ID DESC