SELECT SS.S SCORE, SS.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM(
    SELECT G.EMP_NO, SUM(G.SCORE) S
    FROM HR_GRADE G
    GROUP BY EMP_NO
    ORDER BY S DESC
    LIMIT 1
) SS, HR_EMPLOYEES E
WHERE E.EMP_NO = SS.EMP_NO
    
     