-- 코드를 입력하세요
SELECT b2.TITLE, b2.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
FROM (
    SELECT *
    FROM USED_GOODS_BOARD b
    WHERE DATE_FORMAT(b.CREATED_DATE, "%Y-%m") = '2022-10'
) b2, USED_GOODS_REPLY r
WHERE r.BOARD_ID = b2.BOARD_ID
ORDER BY r.CREATED_DATE, b2.TITLE

