SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM (
    SELECT CATEGORY,
           PRICE,
           PRODUCT_NAME,
           MAX(PRICE) OVER (PARTITION BY CATEGORY) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
)
WHERE PRICE = MAX_PRICE
ORDER BY MAX_PRICE DESC;