SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM
(
    SELECT ROW_NUMBER() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS R
    , CATEGORY, PRICE, PRODUCT_NAME
    FROM FOOD_PRODUCT
)
WHERE R = 1 AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY PRICE DESC